version: '2'

services:
  db:
    image: mysql/mysql-server
    environment: 
      "MYSQL_USER": 'test'
      "MYSQL_PASSWORD": 'test'
      "MYSQL_DATABASE": albums
    ports:
      - "3306:3306"
    restart: unless-stopped